import { useMemo, useState } from "react";
import ClaimDecisionButtons from "./ClaimDecisionButtons";
import {
  type ClaimSourceType,
  type CP2ReviewState,
  type InferredClaimReview,
  type ReviewDecision,
} from "./types";

interface Props {
  clientId: string;
  state: CP2ReviewState;
}

const SOURCE_ORDER: ClaimSourceType[] = [
  "BUYER_PAIN_POINT",
  "INTEL_REPORT_PRIORITY",
  "INTEL_REPORT_COMPETITOR",
  "INTEL_REPORT_PAIN",
  "INTEL_REPORT_OTHER",
];

const SOURCE_FRIENDLY: Record<ClaimSourceType, { label: string; icon: string; desc: string }> = {
  BUYER_PAIN_POINT:         { label: "Buyer Pain Points",          icon: "🎯", desc: "Inferred from your buyers' role, title, and profile data" },
  INTEL_REPORT_PRIORITY:    { label: "Strategic Priorities",       icon: "📌", desc: "Inferred from the company's recent news and strategic initiatives" },
  INTEL_REPORT_COMPETITOR:  { label: "Competitive Landscape",      icon: "⚔️",  desc: "Inferred from competitor activity observed for this account" },
  INTEL_REPORT_PAIN:        { label: "Inferred Pain Points",       icon: "💡", desc: "AI-guessed pain points based on company intel and industry context" },
  INTEL_REPORT_OTHER:       { label: "Other Intel",                icon: "📄", desc: "Additional signals surfaced from the intelligence report" },
};

const DECISIONS: ("ALL" | ReviewDecision)[] = ["ALL", "PENDING", "APPROVED", "CORRECTED", "REMOVED"];

const DECISION_PILL: Record<string, { bg: string; fg: string; border: string }> = {
  ALL:       { bg: "var(--surface-3)", fg: "var(--text-2)", border: "var(--border)" },
  PENDING:   { bg: "#fef3c7",          fg: "#92400e",       border: "#fde68a" },
  APPROVED:  { bg: "var(--good-50)",   fg: "var(--good-700)", border: "var(--good-100)" },
  CORRECTED: { bg: "#fef3c7",          fg: "#92400e",       border: "#fde68a" },
  REMOVED:   { bg: "var(--bad-50)",    fg: "var(--bad-700)",  border: "var(--bad-100)" },
};

const CLAIM_LEFT_BORDER: Record<string, string> = {
  PENDING:   "var(--border-strong)",
  APPROVED:  "var(--good-500)",
  CORRECTED: "#f59e0b",
  REMOVED:   "var(--bad-500,#e0493c)",
};

function ClaimCard({ clientId, claim }: { clientId: string; claim: InferredClaimReview }) {
  const isCorrected = claim.review_decision === "CORRECTED" && claim.corrected_text;
  const borderColor = CLAIM_LEFT_BORDER[claim.review_decision] ?? "var(--border-strong)";
  const isRemoved = claim.review_decision === "REMOVED";

  return (
    <div
      data-testid={`claim-card-${claim.claim_id}`}
      data-decision={claim.review_decision}
      style={{
        background: "var(--surface)",
        border: "1px solid var(--border)",
        borderLeft: `3px solid ${borderColor}`,
        borderRadius: 12,
        padding: "14px 16px",
        display: "grid",
        gap: 10,
        opacity: isRemoved ? 0.55 : 1,
        transition: "opacity 0.2s",
      }}
    >
      {/* Header row */}
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-start" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, minWidth: 0 }}>
          <div style={{
            width: 28, height: 28, borderRadius: 7, flexShrink: 0,
            background: "var(--acc-100)", color: "var(--acc-700)",
            display: "grid", placeItems: "center", fontSize: 11, fontWeight: 800,
          }}>
            {claim.account_domain[0]?.toUpperCase()}
          </div>
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text-2)" }}>{claim.account_domain}</div>
            {claim.contact_id && (
              <div style={{ fontSize: 10, color: "var(--text-3)" }}>Contact {claim.contact_id.slice(0, 8)}…</div>
            )}
          </div>
        </div>
        <span title="This claim was generated by AI — it has not been verified. Your job is to confirm or correct it." style={{
          fontSize: 10, color: "#92400e", fontWeight: 700,
          background: "#fef3c7", border: "1px solid #fde68a",
          padding: "2px 8px", borderRadius: 999, whiteSpace: "nowrap", cursor: "help",
        }}>
          🤖 AI inferred
        </span>
      </div>

      {/* Claim text */}
      <div style={{
        fontSize: 14, fontWeight: 700, lineHeight: 1.5, color: "var(--text)",
        textDecoration: isRemoved ? "line-through" : "none",
      }}>
        {claim.claim_text}
      </div>

      {/* Corrected version */}
      {isCorrected && (
        <div style={{
          fontSize: 13, padding: "8px 12px",
          borderLeft: "3px solid #f59e0b",
          background: "#fffbeb", color: "#92400e",
          borderRadius: "0 6px 6px 0",
        }}>
          <strong>Your correction:</strong> {claim.corrected_text}
        </div>
      )}

      {/* AI reasoning — shown as "why the AI thinks this" */}
      {claim.reasoning && (
        <div style={{
          fontSize: 12, color: "var(--text-3)", lineHeight: 1.5,
          background: "var(--surface-2)", borderRadius: 6, padding: "7px 10px",
          borderLeft: "2px solid var(--border)",
        }}>
          <span style={{ fontWeight: 600, color: "var(--text-2)" }}>Why the AI thinks this: </span>
          {claim.reasoning}
        </div>
      )}

      <ClaimDecisionButtons clientId={clientId} claim={claim} />
    </div>
  );
}

export default function PerClaimView({ clientId, state }: Props) {
  const [decisionFilter, setDecisionFilter] = useState<(typeof DECISIONS)[number]>("ALL");
  const [accountQuery, setAccountQuery] = useState("");
  const [sourceFilter, setSourceFilter] = useState<"ALL" | ClaimSourceType>("ALL");

  const filtered = useMemo(() => {
    return state.inferred_claims_review.filter((claim) => {
      const decisionOk = decisionFilter === "ALL" || claim.review_decision === decisionFilter;
      const sourceOk   = sourceFilter === "ALL" || claim.source_type === sourceFilter;
      const accountOk  = !accountQuery || claim.account_domain.toLowerCase().includes(accountQuery.toLowerCase());
      return decisionOk && sourceOk && accountOk;
    });
  }, [state.inferred_claims_review, decisionFilter, sourceFilter, accountQuery]);

  const groups = useMemo(() => {
    const buckets = new Map<ClaimSourceType, InferredClaimReview[]>(
      SOURCE_ORDER.map((s) => [s, []])
    );
    for (const claim of filtered) {
      buckets.get(claim.source_type)?.push(claim);
    }
    return SOURCE_ORDER.map((source) => ({ source, claims: buckets.get(source) ?? [] }))
      .filter((g) => g.claims.length > 0);
  }, [filtered]);

  const counts = useMemo(() => {
    const map: Record<string, number> = { ALL: 0 };
    for (const d of DECISIONS.slice(1)) map[d] = 0;
    for (const claim of state.inferred_claims_review) {
      map.ALL++;
      map[claim.review_decision] = (map[claim.review_decision] ?? 0) + 1;
    }
    return map;
  }, [state.inferred_claims_review]);

  return (
    <div style={{ display: "grid", gap: 16 }}>
      {/* ── Filters ── */}
      <div style={{
        background: "var(--surface)", border: "1px solid var(--border)",
        borderRadius: 12, padding: "14px 16px",
        display: "flex", flexDirection: "column", gap: 12,
      }}>
        {/* Decision filter pills */}
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: "var(--text-mute)", textTransform: "uppercase", letterSpacing: "0.08em", marginRight: 4 }}>Decision</span>
          {DECISIONS.map((d) => {
            const dp = DECISION_PILL[d];
            const active = decisionFilter === d;
            return (
              <button
                key={d}
                type="button"
                data-testid={d === "ALL" ? "filter-decision-all" : undefined}
                onClick={() => setDecisionFilter(d)}
                style={{
                  padding: "4px 12px", borderRadius: 999, fontSize: 11, fontWeight: 600, cursor: "pointer",
                  background: active ? dp.bg : "var(--surface-2)",
                  color: active ? dp.fg : "var(--text-3)",
                  border: active ? `1.5px solid ${dp.border}` : "1.5px solid var(--border)",
                }}
              >
                {d === "ALL" ? "All" : d.charAt(0) + d.slice(1).toLowerCase()}{counts[d] !== undefined ? ` (${counts[d]})` : ""}
              </button>
            );
          })}
        </div>

        {/* Source + account row */}
        <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
          <label style={{ fontSize: 12, fontWeight: 700, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "center" }}>
            <span>Source</span>
            <select
              value={sourceFilter}
              onChange={(e) => setSourceFilter(e.target.value as typeof sourceFilter)}
              data-testid="filter-source"
              style={{
                padding: "6px 10px", border: "1.5px solid var(--border)", borderRadius: 8,
                fontSize: 12, background: "var(--surface)", color: "var(--text)",
                outline: "none", cursor: "pointer",
              }}
            >
              <option value="ALL">All sources</option>
              {SOURCE_ORDER.map((src) => (
                <option key={src} value={src}>{SOURCE_FRIENDLY[src].icon} {SOURCE_FRIENDLY[src].label}</option>
              ))}
            </select>
          </label>

          <div style={{ flex: 1, minWidth: 200, display: "flex", gap: 8, alignItems: "center" }}>
            <span style={{ fontSize: 12, fontWeight: 700, color: "var(--text-2)", whiteSpace: "nowrap" }}>Account</span>
            <input
              value={accountQuery}
              onChange={(e) => setAccountQuery(e.target.value)}
              placeholder="filter by domain…"
              data-testid="filter-account"
              style={{
                flex: 1, padding: "6px 10px", border: "1.5px solid var(--border)", borderRadius: 8,
                fontSize: 12, background: "var(--surface)", color: "var(--text)",
                outline: "none",
              }}
            />
          </div>
        </div>
      </div>

      {/* ── Claim groups ── */}
      {groups.length === 0 ? (
        <div style={{
          background: "var(--surface)", border: "1.5px dashed var(--border-strong)",
          borderRadius: 12, padding: "48px 24px", textAlign: "center",
          color: "var(--text-3)", fontSize: 14,
        }}>
          No claims match the current filters.
        </div>
      ) : (
        groups.map((group) => {
          const groupTotal = group.claims.length;
          const groupReviewed = group.claims.filter((c) => c.review_decision !== "PENDING").length;
          return (
            <section key={group.source} data-testid={`group-${group.source}`} style={{ display: "grid", gap: 8 }}>
              <div style={{
                display: "flex", justifyContent: "space-between", alignItems: "center",
                padding: "8px 12px",
                background: "var(--surface-2)", borderRadius: 8,
                border: "1px solid var(--border)",
              }}>
                <div>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text)", display: "flex", alignItems: "center", gap: 6 }}>
                    <span>{SOURCE_FRIENDLY[group.source].icon}</span>
                    <span>{SOURCE_FRIENDLY[group.source].label}</span>
                  </div>
                  <div style={{ fontSize: 11, color: "var(--text-3)", marginTop: 2 }}>
                    {SOURCE_FRIENDLY[group.source].desc}
                  </div>
                </div>
                <span style={{
                  fontSize: 11, fontWeight: 700, padding: "3px 10px", borderRadius: 999,
                  background: groupReviewed === groupTotal ? "var(--good-50)" : "#fef3c7",
                  color: groupReviewed === groupTotal ? "var(--good-700)" : "#92400e",
                  border: `1px solid ${groupReviewed === groupTotal ? "var(--good-100)" : "#fde68a"}`,
                  whiteSpace: "nowrap",
                }}>
                  {groupReviewed === groupTotal ? "✓ Done" : `${groupReviewed}/${groupTotal} reviewed`}
                </span>
              </div>
              {group.claims.map((claim) => (
                <ClaimCard key={claim.claim_id} clientId={clientId} claim={claim} />
              ))}
            </section>
          );
        })
      )}
    </div>
  );
}
